### ISSUE TITLE
Weird $ref in exported bundled version with common models

### ISSUE THREAD

**Issue by Sshnyari** [stoplightio/studio#482] opened 2020-07-22 00:57 UTC
**Describe the bug**
I created single API models and common models and referenced them in some endpoints. When I used the export feature (bundled version) I noticed that models defined as common (so in separated files) aren't in the components section like the single API ones. They are defined in one endpoint and referenced by other endpoints using the path to that first endpoint.
I am new to stoplight, so I don't know if this is actually a bug or if my way of using common models is wrong.

**To Reproduce**

1. Create an API, a common model and a single API model
2. Use the common model in two or more endpoints as a $ref
3. Use the single API model in an endpoint (optional)
4. Export a bundled version

Here is the output of the reproduction:
```yaml
openapi: 3.0.0
info:
  title: bundle-bug
  version: '1.0'
  description: desc
  contact:
    name: 'bugging committee :)'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: get users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1users~1%7Bid%7D/get/responses/200/content/application~1json/schema'
      operationId: get-users
      description: get a list of users
  '/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get user
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: user
                type: object
                properties:
                  id:
                    type: string
      operationId: get-users-id
      description: get a single user
  /articles:
    get:
      summary: Get articles
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articles'
      operationId: get-articles
      description: get a list of articles
components:
  schemas:
    articles:
      title: articles
      type: object
      properties:
        id:
          type: string

```

**Expected behavior**
From my short experience with OpenAPI design, I guess that all models should be defined the components section.

**Screenshots**
NA

**Environment (remove any that are not applicable):**
 - Studio version: Desktop 1.13.1
 - OS: Windows 10

**Additional context**
A sample project to recreate the bug is attached
[bundle-tests.zip](https://github.com/stoplightio/studio/files/4957204/bundle-tests.zip)

**Comment by philsturgeon** [comment] 2020-07-23 14:37
Hey @Sshnyari, this looks a little funny at first but this is an export for programatic usage, not a document intended for human reading.

We use https://github.com/APIDevTools/json-schema-ref-parser to handle bundling and exporting, and this is the bundling working as expected. The first instance of the model is kept in place, then all other instances of that same model will point to that. 

It doesn't take an opinionated stance on how to best structure an OpenAPI document for you, or worry about whether it should use components, definitions, or some other structure. It just does the same old thing regardless.

Seeing as it's not a bug I'll close this, but if you have some specific requirements for structuring a single OpenAPI file in a particular way, there are loads of Ref Resolvers around you could play with, and hook them up in some sort of Continuous Integration of CLI process to get the exact results that you need. Studio doesn't tie you into any particular tooling because your files are in your repo, so you're free to work however you like! 🥳

**Closed by philsturgeon** 2020-07-23 14:37 UTC
