### ISSUE TITLE
Display of reusable examples in form mode

### ISSUE THREAD

**Issue by checkin247** [stoplightio/studio#359] opened 2020-03-14 19:09 UTC
**Describe the bug**
A small issue when displaying examples which are referenced.
Its only about how it is displayed, it doesn't affect the usability.
It would be nice though being able to add references in form mode.

**To Reproduce**

1. Add an example to a response using a reference (in code mode).

```
responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                $ref: '#/components/examples/RegistrationCollection'
              schema:
                ...
```

**Expected behavior**
Display the example name instead of the "$ref".

**Screenshots**
In form mode:
![image](https://user-images.githubusercontent.com/12472764/76688687-71fb1d80-662f-11ea-9ac8-c58bbbc570ef.png)
Ok in preview:
![image](https://user-images.githubusercontent.com/12472764/76688692-7aebef00-662f-11ea-8278-d9122c224f78.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.10.2
 - OS: [e.g. Windows 10]
 - Browser: Desktop / Electron

**Additional context**
Does not influence the behaviour

**Comment by philsturgeon** [comment] 2020-06-09 11:59
This is almost a duplicate of #308 but the example you've pasted in isn't valid. I'm sure you tried a few things and this was just one of them, but let's continue the chat on #308 as it's got a valid example of OAS3 which is failing.

**Closed by philsturgeon** 2020-06-09 11:59 UTC
Labels: t/bug
