### ISSUE TITLE
Strings are converted to numbers in samples if they begin by 0

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#302] opened 2020-01-16 11:37 UTC
**Describe the bug**
An attribute is specified as a string :
![image](https://user-images.githubusercontent.com/20415788/72521529-e39b3300-385b-11ea-95bf-463c7c5dcf57.png)
But in the samples, it keeps being converted to a number.
I input:
![image](https://user-images.githubusercontent.com/20415788/72521595-0594b580-385c-11ea-93e1-1f2276bc9ba8.png)
And as soon as I exit the input field, it is converted to a number:
![image](https://user-images.githubusercontent.com/20415788/72521658-1e04d000-385c-11ea-84b7-f337e76454e0.png)

It seems that it exists for some time: I check old versions of the API, and they are already invalid. I would not have seen it if checks about samples would not have reported an issue.

**Environment (remove any that are not applicable):**
 - Studio version: 1.8.1, and it does 
 - OS: W10
 - Browser: Chrome 79 when in browser

This is a blocking problem, as it renders API incoherent when it happens. 
Fortunately for me, it is the only instance of a string containing a number with leading 0 exists, but the only workarount I found is to update the file in code view and immediately push it to source control, then generate the doc..

**Comment by mallachari** [comment] 2020-03-18 17:06
@john-doe-2016 thanks for spotting, that was quite interesting to reproduce and debug. 
Turns out it happened only with leading 0 and following 8s or 9s. Leading 0 forced treating value as octal number while 8 and 9 are out of its scope. That caused removing quotes from yaml value.

Fix should arrive soon.

**Comment by vincent-paing** [comment] 2020-05-18 12:05
Any updates on this fix? Since I live in Myanmar, and our phone number starts with "09". It's a huge bug for me when I have to make an API surrounding phone numbers

**Comment by P0lip** [comment] 2020-05-18 12:19
Apologies for any update.
The fix should be published as the part of the next 1.12 release, supposed to be out very soon.

**Comment by lottamus** [comment] 2020-05-18 17:34
We've just released Studio Desktop [v1.12](https://github.com/stoplightio/studio/releases/tag/v1.12.0) which includes a fix for this issue. Please feel free to re-open if you're still seeing the issue after upgrading.

**Closed by lottamus** 2020-05-18 17:34 UTC
Labels: bug

**Comment by john-doe-2016** [comment] 2020-06-04 12:15
> @john-doe-2016 thanks for spotting, that was quite interesting to reproduce and debug.
> Turns out it happened only with leading 0 and following 8s or 9s. Leading 0 forced treating value as octal number while 8 and 9 are out of its scope. That caused removing quotes from yaml value.
> 
> Fix should arrive soon.

Hi,

Thanks for the correction. Neverthess, it happened with "0037..." in my sample.

I'll test as soon as I can.

Regards

**Comment by john-doe-2016** [comment] 2020-06-04 12:18
For me, it does seem to be ok now.

Thanks.
