### ISSUE TITLE
Studio seems not to be working with WSL2

### ISSUE THREAD

**Issue by M3enjamin** [stoplightio/studio#461] opened 2020-06-19 07:40 UTC
**Describe the bug**
When opening an project existing on the windows subsystem for linux (ie \\wsl$\Ubuntu\...), Studio doesn't show any project files and doesn't seem to be saving any newly created file either.
I tried to open a copy of the same project but on the windows file system and it works fine so it doesn't seem to be a problem with the project.

**To Reproduce**
Open any project via a wsl2 path  (\\wsl$\...)

**Environment (remove any that are not applicable):**
 - Studio version: latest
 - OS: Windows 10

**Comment by philsturgeon** [comment] 2020-06-24 11:57
This seems like a duplicate of #350, so maybe you could help? We were trying to figure out exactly what was going on over there but were always lacking information.

**Closed by philsturgeon** 2020-06-24 11:57 UTC

**Comment by M3enjamin** [comment] 2020-06-30 08:07
Sorry, I checked but I apparently missed the already existing issue. As for the help, I'd be glad to help but I don't really know how...
If you tell me what information you need, I'll provide it.
