### ISSUE TITLE
Export bundled API as YAML/JSON

### ISSUE THREAD

**Issue by benjdl** [stoplightio/studio#150] opened 2019-09-30 15:16 UTC
As a Confluence user, I would like to expose my API documentation on a single page through the existing OpenAPI viewer macro.

The macro needs as input either:
- the url pointing to API definition (normally openapi.json or openapi.yaml)
- or the full JSON/YAML definition to macro body to generate documentation.

**Comment by philsturgeon** [comment] 2019-10-04 09:15
Duplicate of #126

**Closed by philsturgeon** 2019-10-04 09:15 UTC
Labels: enhancement, p:medium
