### ISSUE TITLE
Add support for setting "nullable" keyword on schema objects 

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#132] opened 2019-09-25 15:58 UTC
Add support for the OpenAPIv3 "nullable" keyword through the form-based editor.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-20

## Nullable

Neither OAS2 or OAS3.0 allow `"type: 'null'"` or  `"type: ['null']"`, so if the null type is selected in JSE then we should output the following:

```yaml
# oas2
type: string
x-nullable: true  # the x- means this is an extension

# oas3.0
type: string
nullable: true

# what we do now (JSON Schema) 
type:
  - string
  - 'null'

# oas3.1 deprecated
type: string
nullable: true    # this is deprecated but valid 

# oas3.1 better (same as what we do now)
type:
  - string
  - 'null'
```

😅🤪🤔🤯🤨😞 right? Nobody is excited but the point is the divergence has been solved in 3.1, yay, but until then we have to handle these variations. 

Studio needs to be aware of if its editing an OAS2 or OAS3.0 file, then use the appropriate keywords. We did this for OAS3 `deprecated` vs OAS2 `x-deprecated` recently #223, so it seems like we can add a hack to do something similar. 

It will almost certainly be a hack, and this hack will have limitations. The way studio detects OAS2/OAS3/"JSON Schema" is currently somewhat flawed. If there is `swagger: 2.0` then its OAS2, if `openapi: 3.0.x` then its OAS3, otherwise if it looks like it might be a JSON Schema (type: foo was found) then we'll go with that. This is a bit of a simplification, but its roughly the case. This means, even after this change, JSE will not be able to help anyone who is using $ref to external files for their models, because we have no way of knowing if the $reffed model is "JSON Schema Proper" or "OpenAPI Schema Object".

This is being attacked systematically across all of our tooling post-v2, with "multiple dialect support". This issue is about giving us a quick win on this nullable situation ASAP.

**Comment by P0lip** [comment] 2019-09-25 23:35
@philsturgeon Is this actually a blocker? :thinking: 
One can always type it manually in a write panel.

**Comment by philsturgeon** [comment] 2019-09-26 00:32
It’s a blocker for people who don’t know the OpenAPI spec off by heart but want to use studio to solve common tasks. This one is gonna be confusing a lot of people, I’m super surprised we’ve only heard about it once!

It’s also a good chance for us to abstract nullable or type array with null, depending on if it’s openapi or JSON Schema. People won’t know which thing to write but a UI can solve that problem.

**Comment by wmhilton** [comment] 2019-09-26 14:42
@philsturgeon it appears that this repo is missing the label descriptions present in the `studio-internal` repo, which is the cause of your confusion. Here's the agreed upon meaning of these labels:

![image](https://user-images.githubusercontent.com/587740/65698182-22597300-e04a-11e9-8a88-96ce8e94f64c.png)

By the definitions our team uses, this is `sev:major`.

**Comment by wmhilton** [comment] 2019-09-26 14:42
I'll update the label descriptions.

**Comment by philsturgeon** [comment] 2019-09-26 15:11
I’m aware of the descriptions and was using them. A workaround that is not obvious to the average user is still a blocker to them IMO. They can’t get things done until somebody from support tells them what to do... 

 Feel free to drop it to critical but it’s way up there, that’s all I’m trying to communicate.

**Comment by wmhilton** [comment] 2019-09-26 15:13
I think our definitions of "critical functionality" are misaligned. Critical funcitonality is not "nullable" keyword. It's stuff like "being able to log in" and "being able to save files without the program crashing".

**Comment by wmhilton** [comment] 2019-09-26 15:16
stuff like "the desktop build artifact for OSX actually gets produced before we publish to npm"

**Comment by P0lip** [comment] 2019-09-26 15:38
>  A workaround that is not obvious to the average user is still a blocker to them IMO.

Yeah, I absolutely understand it and would like to have this feature implemented. On the other hand, however, if you put that issue next to some memory leaks (that are rather rare for the vast majority of users, but still, occurring when certain conditions are met, i.e. huge projects with lots of $refs), it's clear it's less severe.

**Comment by philsturgeon** [comment] 2019-09-26 15:40
Whatever you folks decide is absolutely fine. I do not want to talk about fixing bugs I want to fix bugs. :D

**Comment by wmhilton** [comment] 2019-09-26 15:44
this isn't a bug it's a feature

**Comment by coatesap** [comment] 2019-10-18 10:05
Just to add some extra detail to this, the way that studio currently outputs nullable types definitely breaks the [specification](https://swagger.io/docs/specification/data-models/data-types/) on a couple of levels. Currently, this is the YAML produced:

```yaml
type:
  - string
  - 'null'
```

1) Lists are not allowed:

![image](https://user-images.githubusercontent.com/1926626/67085444-bf658280-f196-11e9-99e0-79d583418ad3.png)

2) And null is specifically prohibited as a type:

> Note that there is no null type; instead, the nullable attribute is used as a modifier of the base type.

This is quite frustrating behaviour, as the output errors in validation tools like https://github.com/thephpleague/openapi-psr7-validator and has to be corrected by hand.

**Comment by philsturgeon** [comment] 2019-10-24 22:45
@coatesap what you are talking about is a slight different issue, being tracked as https://github.com/stoplightio/studio/issues/190.

**Comment by handrews** [comment] 2019-11-19 03:51
Here's the proposed clarification of `nullable` that is likely to go into 3.0.3: https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md

**Comment by lucasmoreno** [comment] 2020-04-06 14:40
@philsturgeon is there any planning to fix this issue in the near future?

**Comment by Dakwamine** [comment] 2020-04-07 09:46
Just wanted to add that editing the values in the UI erases the nullable keyword in the code, which is inconvenient.

**Comment by philsturgeon** [comment] 2020-04-07 10:04
@Dakwamine @lucasmoreno yeah absolutely. We’ve been planning dialect support for Oas2/3/3.1 and all the important JSON Schema drafts. If this issue looked quiet it’s because that’s a big load of work and it’s mostly been happening on slack. The requirements doc is ready, the design doc is coming. 

Between the pandemic and a huge release coming this month, we’ve been somewhat halted progress on the design doc. It’ll be picking up again soon.

**Comment by philsturgeon** [comment] 2020-04-09 15:41
See https://github.com/stoplightio/studio/issues/388 which will solve this and the type array issue all in one.

**Comment by kurko** [comment] 2020-06-02 13:36
FYI, `nullable` was [dropped in 3.1](https://github.com/OAI/OpenAPI-Specification/pull/2246) so you might want to ensure feature flags on this one.

**Comment by philsturgeon** [comment] 2020-09-03 15:43
Closing this one in favour of solving it all in #388.

**Closed by philsturgeon** 2020-09-03 15:43 UTC
Labels: cs/reported, p/high, t/enhancement, team/void-crew
