### ISSUE TITLE
Multiple types for schemas are generated as a list instead of oneOf

### ISSUE THREAD

**Issue by kag0** [stoplightio/studio#190] opened 2019-10-11 23:53 UTC
Disclaimer: I'm checking this against https://editor.swagger.io/ with only a quick reading of the spec.

**Describe the bug**
The editor allows multiple types to be defined in a list for a field in a schema, but it should represent that using `oneOf`. When you do manually use `oneOf`, you lose the ability to mark the field as required or add any constraints to primitive types.

**To Reproduce**

1. Given this OpenAPI document 
```yaml
openapi: 3.0.0
info:
  title: Example
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /example:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type:
                  - string
                  - number
```
2. Click "string or number" in the response body schema in the "forms" view
3. See that that looks normal, but won't this file won't render elsewhere.

**Expected behavior**
The editor raises an error and suggests to correct to using `oneOf`

**Comment by philsturgeon** [comment] 2019-10-24 22:47
Another week and 3.1.0-RC1 should be around, or at the very least https://github.com/OAI/OpenAPI-Specification/pull/1977 will be merged and this nightmare will be on its way to being over. 

Context: https://stoplight.io/blog/openapi-json-schema/

This should be a oneOf if `openapi: 3.0.*` is set.

**Comment by philsturgeon** [comment] 2020-03-03 18:11
For those watching, this is being worked on as a much larger effort to support various "Dialects" correctly at various stages in various tools throughout the ecosystem. Multiple JSON Schema drafts, multiple OpenAPI-flavours, etc. 

Many people expect this exact functionality, and many consider it a bug, so... 😅 It's tough, but we've got some very smart people on this one.

**Comment by kag0** [comment] 2020-03-03 19:39
> Many people expect this exact functionality, and many consider it a bug, so... sweat_smile 

My 2c is that the output should always be valid for whatever the target format is, but aside from that I trust you guys will find a good compromise.

**Comment by philsturgeon** [comment] 2020-03-03 21:31
@kag0 yep that's how some people feel and others have a slightly different view. We have generally allowed slightly incorrect but commonly accepted stuff, like this, as many tools support it. For example, ReDoc, another documentation tool, allows type arrays even though OpenAPI does not. 

This superset is expected functionality for many people, so ripping that away from them would be hugely problematic. This is why we're working on multiple dialect support, so you can pick the exact dialect you want, or a loosey goosey superset dialect, and everyone gets what they want. Like I said that's tough to do, so it'll take a bit of time.

**Comment by philsturgeon** [comment] 2020-04-09 15:08
Well this message aged badly. 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/67381/78910001-301d9580-7a7c-11ea-848b-35a754921761.png">

Still no OpenAPI 3.1.0-RC0, although we're expecting it any day now. Might literally be today, but we can't keep this waiting game going. I am going to turn #132 into an issue that resolved this in the short term, which makes this a duplicate of that. Subscribe over there if you're interested in seeing when we get a quickfix in.

**Closed by philsturgeon** 2020-04-09 15:08 UTC
Labels: bug, p:high, sev:major
