### ISSUE TITLE
Field disappears when adding a property to a model

### ISSUE THREAD

**Issue by paulyk1983** [stoplightio/studio#123] opened 2019-09-19 16:09 UTC
**Describe the bug**
When I am trying to add a new property to a model using the form editor, the field often disappears (within one second) before I can finish typing in the name for that field, forcing me to repeat the process again. This makes adding new properties extremely frustrating.

**To Reproduce**

1. Add a new model or edit an existing one
2. Using the form editor view, click the plus icon to begin adding a new property
3. Wait one or two seconds, and the field disappears

**Expected behavior**
The field should not disappear and allow me to type in the name of the property.

**Screenshots**
n/a

**Environment (remove any that are not applicable):**
 - Studio version: v1.1.1
 - OS: [e.g. Windows 10]
 - Browser: n/a using desktop version

**Additional context**
none

**Comment by marbemac** [comment] 2019-09-25 05:08
Hi @paulyk1983, thanks for the report! We're having trouble reproducing, any chance you could try a few things out?

1) does this occur for a net new project with a single model file in it?
2) embedded model (e.g. part of an open api file) or standalone json schema file?
3) any other distinguishing notes that might help us reproduce/identify the issue?

This is on v1.1.4:

![Sep-25-2019 00-05-34](https://user-images.githubusercontent.com/847542/65570938-7b30ea80-df28-11e9-9a0e-863a03f2f83f.gif)

**Comment by paulyk1983** [comment] 2019-09-25 19:57
Hi. This happens only when working with embedded models and when auto-save is enabled.

**Comment by StoplightDeb** [comment] 2019-10-15 20:19
Not able to reproduce this one - regardless of `auto-save` status, the empty fields persist and do not disappear - closing.

**Closed by StoplightDeb** 2019-10-15 20:19 UTC
Labels: bug, p:highest
