### ISSUE TITLE
Missing fields to match linting notices/errors

### ISSUE THREAD

**Issue by adamculp** [stoplightio/studio#145] opened 2019-09-27 19:41 UTC
**Describe the bug**
Despite there being multiple warnings and errors associated with linting, there are no corresponding fields in the GUI editor to eliminate them.

**To Reproduce**

1. Create API and define
2. Notices and errors in lower-right make mention of non-empty 'tags' array and missing 'operationId', as well as request body not having $ref (which leads down a rabbit hole of additional endpoints missing $ref.
3. There are no visible places in GUI to edit/add these items to calm the notices and errors.
4. There are no visible places to edit the linting config to quiet these notices.

**Expected behavior**

It would be nice if either the studio user could have a place to quiet these notices, or if they should be used a way to edit the items causing notices.

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.1
 - OS: Ubuntu 18.04
 - Browser: 71.0.3578.98 (Official Build) (64-bit)

**Comment by philsturgeon** [comment] 2020-03-03 18:14
@adamculp sorry for letting this fall through the cracks, but got some good news. We're working on "ignore this warning" for specific linter errors (over on the Spectral repo, then we add buttons to Studio) 

The remainder of this seems like a duplicate of https://github.com/stoplightio/studio/issues/104, so let's close this down. I would love to have the warnings take me to the right form component, totally hear you!

**Closed by philsturgeon** 2020-03-03 18:14 UTC
Labels: bug
