### ISSUE TITLE
Switching git branches after commit fail discards changes without warning

### ISSUE THREAD

**Issue by marbemac** [stoplightio/studio#277] opened 2019-12-18 23:29 UTC
**Describe the bug**

If the commit process fails, then subsequently switching branches will discard changes without notifying the user.

**To Reproduce**

1. Open a git project in studio.
2. Make a change, and commit the change. Make sure commit fails (for example, set branch protection in backing VCS so that cannot push to it).
3. Switch branches, note changes are discarded without warning.

Seems that isomorphic git does not throw that `CheckoutConflictError` error on checkout if previously had a commit fail? Not sure.

**Expected behavior**

Should show the discard changes warning:

<img width="1117" alt="Screen Shot 2019-12-18 at 5 25 49 PM" src="https://user-images.githubusercontent.com/847542/71131975-da1a9e80-21bb-11ea-8e14-7bb56155e0cc.png">

**Screenshots**

![Dec-18-2019 17-25-05](https://user-images.githubusercontent.com/847542/71131990-e69ef700-21bb-11ea-8cc4-2b399c6d9b1b.gif)

**Comment by wmhilton** [comment] 2019-12-19 20:24
Working theory: changes are still _staged_ after failed commitpush. Not 100% sure why that would fool the conflict detection though, but that's my theory as to the cause.

**Comment by marbemac** [comment] 2019-12-20 13:01
@wmhilton can you confirm this was fixed and included in 1.7.1?

**Comment by rossmcdonald** [comment] 2019-12-20 14:43
@marbemac I have confirmed this is now fixed with v1.7.1.

**Closed by rossmcdonald** 2019-12-20 14:43 UTC
Labels: bug, customer reported, p:high
