### ISSUE TITLE
More Visibility into "Processing" and Analyze later

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#90] opened 2019-09-05 17:18 UTC
**User story.**

As a studio web or desktop user I want to know what is happening when Studio is "Processing", so I can start trying to figure out what might be wrong if processing stops at some point. 

**Is your feature request related to a problem?**

Various users have reported "Processing" stage just stops for some unknown reason.

**Describe the solution you'd like**

Instead of just saying "Processing" with a number next to it (what is that number) we should be way more informative of whats going on.

1. Cloning repository
  - Connecting to GitHub
  - Pulling from branch
  - whatever things git might say
  - Writing to local storage... OOPS ran out of space! 
2. Analyzing 
  - Indexing the filesystem
  - reading relevant files
  - building a graph
  - A progress bar showing how many files the analyzer has run, and a link to What does "Analyzing" mean? which takes them to Studio docs which explains the concept. 

If we can make 2 be optional and happen later, that would be amazing. I'd love to be able to work with my files directly before the analyzer is done. Maybe only the Files tab is enabled, and the Docs and API tabs are disabled with a tooltop showing "Analyzer is still running" or something.

**Comment by michaelklopf** [comment] 2019-10-04 12:28
Hi Stoplight team,

I'm working locally with Stoplight Studio and I opened my local project folder with it. After that the processing bar is shown. The problem is that it takes forever / freezes / shows a blank page.

This is the error in the dev tools when closing the app and opening again:
<img width="1911" alt="image" src="https://user-images.githubusercontent.com/2892138/66207168-59ff9500-e6b2-11e9-85ac-4d50696b0434.png">

The (I guess) Electron browser stops processing due to a potential out-of-memory crash. Pressing the button to continue execution finishes the process after a while and the project is opened.

Doing this the first time was even worse, I deleted the node_modules and vendor folder and the process could be finished.

You probably should add the possibility to ignore these folders to speed up the processing part.

Kind regards,

Michael

**Comment by P0lip** [comment] 2019-10-07 13:07
@michaelklopf We've added lazy $ref resolving recently, which should reduce the startup time.

> I deleted the node_modules and vendor folder and the process could be finished.

Agreed :+1: Noted!

**Comment by philsturgeon** [comment] 2019-10-08 10:13
@P0lip maybe we could spin out a new issue here and ignore anything in the .gitignore? Many IDEs do this, often as an option, but if it’s specifically ignored by git we probably don’t care about it.

**Comment by P0lip** [comment] 2019-10-10 23:06
> @P0lip maybe we could spin out a new issue here and ignore anything in the .gitignore? 

@philsturgeon yeah, that sounds like a safe assumption to make.
@marbemac @wmhilton what do you think?
Might be slightly tricky implementation-wise, but if we do it right, the benefit is likely to be huge (i.e. node_modules or vendor directories excluded by default, without any filters).

**Comment by P0lip** [comment] 2020-03-11 15:31
I believe this is no longer needed. The initial processing process has been vastly improved recently and it's much more stable now.
Going to close it out.

**Closed by P0lip** 2020-03-11 15:31 UTC
Labels: customer reported, enhancement, p:high

**Comment by philsturgeon** [comment] 2020-03-11 15:43
I agree, it's super quick now! Well played.
