### ISSUE TITLE
API Previous out of order

### ISSUE THREAD

**Issue by nasht00** [stoplightio/studio#510] opened 2020-10-28 11:21 UTC
**Describe the bug**
My API has a list if query parameters.  
In both the "Form" and "Code" views, the order is in sync.  
In the "Preview" pane however they are completely out of order.

**Expected behavior**
It is easier to follow if all 3 views are in sync.

**Screenshots**
<img width="616" alt="Screen Shot 2020-10-28 at 13 19 55" src="https://user-images.githubusercontent.com/329834/97429570-46a81300-1920-11eb-98d4-09a2a62347f5.png">

<img width="391" alt="Screen Shot 2020-10-28 at 13 20 33" src="https://user-images.githubusercontent.com/329834/97429632-5d4e6a00-1920-11eb-91cd-160d79fc1567.png">

<img width="602" alt="Screen Shot 2020-10-28 at 13 20 53" src="https://user-images.githubusercontent.com/329834/97429656-693a2c00-1920-11eb-8313-459c0dde7b8b.png">

**Environment (remove any that are not applicable):**
 - Studio version: Version 2.1.0 (2.1.0.66630)

**Comment by nasht00** [comment] 2020-10-28 11:22
Now that I look more closely, it seems in the previous pane they are in alphabetical order. Not just what's the logic behind this ...

**Comment by philsturgeon** [comment] 2020-11-02 19:10
Do you need them to be in the defined order instead of alphabetical order?

**Comment by nasht00** [comment] 2020-11-05 08:53
@philsturgeon Yes, when defining the parameters, I usually give some thoughts to the order. For example pagination-related parameters are at the end (`limit`, `bookmark`, `orderedBy`), things that relate to each other are next to each other (`expiresBefore`, `expiresAfter`).

**Comment by philsturgeon** [comment] 2020-11-05 19:02
I gotcha, this is a duplicate of https://github.com/stoplightio/studio/issues/147 I think, as lots of stuff should be ordered by defined, not ordered alphabetically. Can you subscribe to that one for updates?

**Closed by philsturgeon** 2020-11-05 19:02 UTC
