### ISSUE TITLE
Modifying path parameter values using parameter editor returns to API root

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#215] opened 2019-10-23 21:35 UTC
**To Reproduce**

- **Within Studio web**, modify path parameter using param editor
- Click away

![ezgif-4-9919910ecf96](https://user-images.githubusercontent.com/4060903/67436010-0c8c8e80-f5b3-11e9-9fc1-33653706283e.gif)

Strangely enough this doesn't happen when editing the parameter directly in the path. Super annoying when this happens, though.

**Comment by marbemac** [comment] 2019-10-23 23:35
I think that this might also be web only.

**Comment by rossmcdonald** [comment] 2019-10-24 12:35
@marbemac Yep, I'm unable to reproduce using latest desktop.

**Comment by dgrstl** [comment] 2019-11-08 12:45
This still disrupts demos from time-to-time.

**Comment by StoplightDeb** [comment] 2020-01-29 21:13
@mallachari - I am still seeing weirdness when modifying the path parameter.  Instead of going to the API root, it jumps back to the `Name...` field. [Video](https://drive.google.com/open?id=17D3BdXvi23W_MRkb-DCazAwRFMTqgGIj)

**Comment by mallachari** [comment] 2020-01-30 14:17
@StoplightDeb this happens as the component is rerendering because of new path node. It's unrelated to this issue and quite difficult to overcome. The focus on name happens because of autofocus but changing it wouldn't help as it still needs to rerender.
@chris-miaskowski do you agree?

**Comment by StoplightDeb** [comment] 2020-01-30 15:46
@mallachari - I see - I thought it could be related as clicking on param properties still jumped elsewhere 😆 Will wait for @chris-miaskowski opinion.

**Comment by chris-miaskowski** [comment] 2020-01-31 12:43
@mallachari is right, it's unrelated but great spot @StoplightDeb.

The fix is actually awesome, we had that bug for a looong time and it wasn't trivial to fix. Good job @mallachari!

Closing as looks good in RC. No new cases in regression.

**Closed by chris-miaskowski** 2020-01-31 12:43 UTC
Labels: bug, customer reported, p:high
