### ISSUE TITLE
Unable to publish personal Github projects from Studio

### ISSUE THREAD

**Issue by hirenoble** [stoplightio/studio#85] opened 2019-09-03 19:33 UTC
**Describe the bug**
While trying to publish the docs getting an error.

**To Reproduce**

1. Click on publish

**Expected behavior**
Published documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/3747836/64202791-35b05e80-ce4f-11e9-97d4-054035cfab2a.png)

**Environment (remove any that are not applicable):**
 - Browser: Chrome

**Comment by rossmcdonald** [comment] 2019-09-03 19:35
@hirenoble Was this a personal project, or was it under an organization?

**Comment by marbemac** [comment] 2019-09-04 05:02
Quick follow-up for whoever picks this up - confirmed at least in my preliminary testing that this seems to be an issue with personal github projects - organizational projects seem to be OK.

**Comment by casserni** [comment] 2019-09-06 19:04
Was able to fix the issue and we should hopefully have a patch out shortly!

**Comment by rossmcdonald** [comment] 2019-09-10 04:14
This was fixed with v1.1.1. @hirenoble Let us know if you run into any further issues publishing personal projects.

**Closed by rossmcdonald** 2019-09-10 04:14 UTC
Labels: bug, p:highest, sev:critical

**Comment by hirenoble** [comment] 2019-09-10 04:18
Thank you @rossmcdonald @marbemac @casserni !!
