### ISSUE TITLE
Error when publishing: Variable "$build" got invalid value

### ISSUE THREAD

**Issue by nirsoffer** [stoplightio/studio#141] opened 2019-09-27 15:51 UTC
When publishing, the following error is presented:

```
Variable "$build" got invalid value [{ buildnode: [object], changelog: [array], action: "added", semver: "major" }, { buildnode: [object], changelog: [array], action: "added", semver: "major" }, { buildnode: [object], changelog: [array], action: "modified", semver: "patch" }, { buildnode: [object], changelog: [array], action: "modified", semver: "major" }, { buildnode: [object], changelog: [array], action: "removed", semver: "major" }, { buildnode: [object], changelog: [array], action: "removed", semver: "major" }]; expected type changecontext at value[3].changelog[0].context..
```

**Comment by rossmcdonald** [comment] 2019-09-27 15:55
@nirsoffer Can you provide us with more information?

**Comment by nirsoffer** [comment] 2019-09-27 17:14
`Variable "$build" got invalid value [{ buildnode: [object], changelog: [array], action: "added", semver: "major" }, { buildnode: [object], changelog: [array], action: "added", semver: "major" }, { buildnode: [object], changelog: [array], action: "modified", semver: "patch" }, { buildnode: [object], changelog: [array], action: "modified", semver: "major" }, { buildnode: [object], changelog: [array], action: "removed", semver: "major" }, { buildnode: [object], changelog: [array], action: "removed", semver: "major" }]; expected type changecontext at value[3].changelog[0].context..`

is all that I got. I am not sure what happened to the platform - it was working ok a few months ago - and now it's fairly broken.

additionally, thousands of newlines into the YAML file have been added for no reason and I had to remove them manually. That wasn't fun.

**Comment by chris-miaskowski** [comment] 2019-10-01 13:12
@lottamus I will need steps to reproduce or steps to test. Can you please fill up the issue?

**Comment by nirsoffer** [comment] 2019-10-01 15:22
Sadly this is still happening - let me know if there's anything I can supply; as of now, sadly, the system is not usable to me.

**Comment by chris-miaskowski** [comment] 2019-10-02 12:18
Hi nirsoffer, we have tested a similar case on our staging environment and a fix for this bug should come with the upcoming release (scheduled for today).

I will close this issue for now but if you still have the same problem after the release please let us know. For us to help you (if the bug persists) it would be very useful to get insight into your project (files, models, APIs). 

If your project is private and you cannot share it with us then it would be helpful to see a "minimal failing setup". If you could provide us with some fake data that causes publishing to fail, we would have a better chance figuring the problem out.

CC: @StoplightDeb @P0lip @rossmcdonald 

PS. this is a dulicate of https://github.com/stoplightio/app-gen3/issues/431

**Comment by nirsoffer** [comment] 2019-10-07 08:21
@chris-miaskowski  unfortunately this is still occurring. You might be able to see the files the project is based on at https://github.com/nirsoffer/advertima-knock-knock

This is sadly blocking my usage of Stoplight and I will have to use alternative solutions. It's a shame. It used to work pretty well before the new version.

**Comment by chris-miaskowski** [comment] 2019-10-07 08:45
Hey @nirsoffer thanks for sharing the repository and sorry for the problems you have with the Studio. 
I confirm that I was able to see the exact problem with the repository you've provided. I'm reopening the issue and we'll keep you updated.

CC: @lottamus @ssspear

**Comment by nirsoffer** [comment] 2019-10-07 08:52
@chris-miaskowski please also be advised that this spec was entirely created inside the stoplight studio.

**Comment by StoplightDeb** [comment] 2019-10-08 20:54
@lottamus - I haven't been able to reproduce this so far, but does this need to wait on #490  to go through?

**Comment by StoplightDeb** [comment] 2019-10-08 21:36
All right, #490 is in and I can't make this error happen anymore after trying - cautiously optimistic at this point, so closing this out for now.

**Comment by lottamus** [comment] 2019-10-08 21:43
Thanks @StoplightDeb!

@nirsoffer @chris-miaskowski the fixed for this issue will be included in tomorrow's (Oct 9th) release.

**Comment by chris-miaskowski** [comment] 2019-10-15 09:29
I've tested on our `staging` today and it looks good. I really want this to be fixed for you @nirsoffer! I hope the fix we've implemented will now resolve the problem for you. Release day is tomorrow and I expect it to be fixed in production tomorrow.

@collinbachi it might be a good idea to give @nirsoffer access to our staging environment if the issue is not resolved. It might be helpful to see if that same problem occurs on that environment or is it only production.

**Closed by chris-miaskowski** 2019-10-15 09:29 UTC
Labels: blocked, bug, customer reported, env:production, sev:blocker

**Comment by nirsoffer** [comment] 2019-10-21 08:17
Seems to work on my end now! thanks!

**Comment by chris-miaskowski** [comment] 2019-10-21 08:21
That's amazing, that makes us so happy! Thank you for helping us to identify the problem!

**Comment by nirsoffer** [comment] 2019-10-21 08:40
thanks for helping :)
