### ISSUE TITLE
Bug on publish projects

### ISSUE THREAD

**Issue by gabrieldissotti** [stoplightio/studio#418] opened 2020-05-13 00:22 UTC
**Describe the bug**
I cant publish a project

**To Reproduce**

1. Create an API project 
2. Click on Publish and login
3. The applications will show a new window in url: https://stoplight.io/p/docs

**Expected behavior**
Get a public link of documentation

**Screenshots**

(Step 2)
![- Captura de tela de 2020-05-12 21-13-10](https://user-images.githubusercontent.com/33178519/81757523-8aec4780-9495-11ea-91c6-388cd4cc4d92.png)

(Step 3) 
![ Captura de tela de 2020-05-12 21-13-35](https://user-images.githubusercontent.com/33178519/81757515-8758c080-9495-11ea-8288-510fd716cb88.png)

**Environment (remove any that are not applicable):**
 - Studio version: Web
 - OS: Ubuntu 19.10
 - Browser: Chrome

**Additional context**

![I'm authenticated](https://user-images.githubusercontent.com/33178519/81757642-f0d8cf00-9495-11ea-80e3-dea3b9287f22.png)

I have created my account today (2020-05-12) and verified my e-mail before create the project.

**Comment by gabrieldissotti** [comment] 2020-05-13 00:30
Now I have created a project in github, then I have created a project in spotlight studio clonning this repository, finally I can publish my project, therefore, the error occurs just when a create a project without a github repository. Can be my OS that not shows the login modal correctly.

**Comment by amrdraz** [comment] 2020-05-13 22:22
It's not OS specific I experience the same thing

**Comment by alexhalliday** [comment] 2020-05-15 21:32
Same issue for me.

**Comment by ijarinz** [comment] 2020-05-16 00:14
Related to #340

**Comment by rossmcdonald** [comment] 2020-05-18 15:43
This is a duplicate of #340. Please see that issue for a workaround and more details.

**Closed by rossmcdonald** 2020-05-18 15:43 UTC
Labels: bug
