### ISSUE TITLE
Form for standalone model's adds an extra "value" property to examples

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#176] opened 2019-10-08 15:49 UTC
**Reproduce**

1. Create a standalone model
2. Add an example
3. Notice the result has an extra "value" property nested in each example:

```yaml
x-examples:
  example:
    value:
      latitude: 123
      longitude: 456
```

This is valid for embedded openapi 3 definitions, but not for standalone json schema models.

**Comment by marbemac** [comment] 2019-10-10 04:18
@lottamus @ssspear can we get this scheduled for v1.2.1?

**Comment by lottamus** [comment] 2019-10-10 04:36
@marbemac @ssspear looks like it's coming from the form view: https://github.com/stoplightio/studio-internal/commit/2a84abf35e6cc9c68bd58f744e5c099dbd927eb8#diff-5c6b173215ac8c3ccee0f3b7ab39ae44R105 which is also being used by standalone models: https://github.com/stoplightio/studio-internal/blob/2a84abf35e6cc9c68bd58f744e5c099dbd927eb8/src/components/FormJsonSchema/index.tsx#L30

Should update the logic to only add the `value` property for oas3 files: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#example-object

**Comment by marbemac** [comment] 2019-10-14 15:22
@lottamus this is a standalone model file - so it's independent of oas3 versus oas2 right?

**Comment by lottamus** [comment] 2019-10-14 15:41
@marbemac correct but it's using the same form components so this logic needs to be flipped :https://github.com/stoplightio/studio-internal/commit/2a84abf35e6cc9c68bd58f744e5c099dbd927eb8#diff-5c6b173215ac8c3ccee0f3b7ab39ae44R105

**Comment by StoplightDeb** [comment] 2019-11-07 17:35
@ssspear - I'm still seeing `value` on current staging environment (web & app), so moving this back over

**Comment by lottamus** [comment] 2019-11-07 17:36
@StoplightDeb the issue isn't seeing "value" in the read view. The issue was that the forms were incorrectly adding the "value" property

**Comment by lottamus** [comment] 2019-11-07 17:39
Updated the title + description to reflect

**Comment by StoplightDeb** [comment] 2019-11-07 17:40
@lottamus thanks for updating it

**Closed** 2019-11-12 05:32 UTC
Labels: bug, bug:regression, customer reported, p:medium, qa approved
