### ISSUE TITLE
While defining Model Schema, things disappear

### ISSUE THREAD

**Issue by adamculp** [stoplightio/studio#142] opened 2019-09-27 18:19 UTC
**Describe the bug**

**To Reproduce**

1. After creating a Model
2. Click to add a new items to Schema
3. Sometimes before finishing the item name, or after clicking away, the item just created disappears
4. Usually works the 2nd time.
5. Rinse, repeat

**Expected behavior**
I would expect that as I'm creating a new item in schema it would not disappear, ever.

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.1
 - OS: Linux - Ubuntu 18.04
 - Browser: Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
Not sure if this was caused by previously defined paths, though seems like it shouldn't be.

**Comment by marbemac** [comment] 2019-10-02 05:17
Hi @adamculp, thanks for the report and your patience. Going to close this as a duplicate of #123 - if you feel that this case is different feel free to re-open. In general we're going to tackle this one asap!

**Closed by marbemac** 2019-10-02 05:17 UTC
Labels: bug, p:highest
