### ISSUE TITLE
Mocking not working in Studio with self referencing objects

### ISSUE THREAD

**Issue by amiika** [stoplightio/studio#483] opened 2020-08-04 08:08 UTC
**Describe the bug**

Mocking does not work in Stoplight Studio with separate model objects that use self references.

**To Reproduce**

1. Given this OpenAPI document '...'

Create self referencing object in separate model like:
```
      "User": {
        "title": "User",
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "parent": {
            "$ref": "#/components/schemas/User"
          }
        }
      }
```

And add it to some response ...

2. Click this button '....'

Try mocking using static generation

3. See error

Your schema contains $ref. You must provide specification in the third parameter.

**Expected behavior**

Expecting object with maybe one level of recursion or so.

**Environment (remove any that are not applicable):**
 - Studio version 1.13.1

**Comment by philsturgeon** [comment] 2020-08-05 11:00
Thanks for reporting this @amiika. We're already aware of the problem and have a partial solution, we're just working on finishing it all up nicely and testing it. We'll mark this issue as closed when it's in production (if you're using Studio Web) and you'll see the change float down to Studio Desktop in an upcoming release.

**Comment by philsturgeon** [comment] 2020-12-17 16:07
There have been a lot of reference issues solved over the last few months so this should be fine. If not, please contact support with more information and a fully reproduceable case because currently this example looks like it might be invalid. A model cannot reference stuff out of another OpenAPI file without referencing the file its trying to get stuff out of, but I can't tell if thats what you're trying to do.

Either way, hopefully this is solved, or we'll find out more information, but this issue tracker is going away and I'd rather mention this and close the issue than let it be autoclosed when we disable it. 👋

**Closed by philsturgeon** 2020-12-17 16:07 UTC
